### ISSUE TITLE
Posibilidad de version Linux

### ISSUE THREAD

**Issue by corvusd** [AugustoRuiz/WYZTracker#2]
Hola,
primero de todo darle las gracias por su inmenso aporte a la comunidad!
Seria posible compilar su programa con mono, de forma nativa para linux?
Muchas gracias! :)

**Comment by AugustoRuiz** [comment]
Hola,

El problema es que las APIs utilizadas para usar el teclado MIDI y de acceso al registro para asociar extensiones son propias de Windows, y el soporte de mono a WinForms no es tan bueno como sería deseable, y no preveo migrar a otro tipo de interfaz, como puede ser Qt.

Está en desarrollo una versión íntegramente realizada usando HTML5, CSS3 y Javascript, que usará las APIs de Audio para generar el sonido. Además tiene implementado Undo y Redo. Esta versión no tiene fecha, pero ya está implementada a un 50%. 

Cuando consiga que los controles de volumen funcionen como deben (ahora mismo están implementados con d3), avanzará más rápidamente.

**Comment by corvusd** [comment]
Un trabajo bestial compañero. Muchas gracias por la rápida respuesta. Espero que vaya bien el desarrollo. Y si es multiplataforma pues mejor! :) Me estoy apañando con wine, parece que en principio va bien. No tengo teclado MIDI pero por lo demás parece que va bien. Saludos!
