### ISSUE TITLE
Requisito openal32.dll

### ISSUE THREAD

**Issue by mvac7** [AugustoRuiz/WYZTracker#8]
Hola Augusto.
Me he descargado la ultima versión del tracker (2.0.1.3) y la estoy ejecutando en un PC/64bits con Windows 10.
No me muestra nada y en el log me marca que no encuentra la librería openal32.dll
He buscado por internet y me salen muchas referencias de sites de descarga de ficheros, pero desconozco si son fiables.
He instalado la ubicada en https://openal.org/ pensando que es el lugar oficial (en una [consulta en la WEB de ubisoft](https://www.ubisoft.com/es-es/help/heroes-of-might-and-magic-3-hd/connectivity-and-performance/article/openal32dll-was-not-found-error-for-heroes-of-might-and-magic-iii-hd-on-steam/000100786) la recomiendan), y me funciona perfectamente.
Te comento todo esto por si te sirve para añadirlo en la documentación como requisito.
Gracias y un saludo!

**Comment by AugustoRuiz** [comment]
Hola,

Lo añadiré. ¡Muchas gracias!

**Comment by AugustoRuiz** [comment]
Añadido al Readme.md.
